{% set name = "apache-airflow-providers-hashicorp" %}
{% set version = "4.3.1" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/apache_airflow_providers_hashicorp-{{ version }}.tar.gz
  sha256: 8bf46da4c75a344dce5a95b3096a5430b43f61cede8fee01cf50620e2b1cfb7b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - flit-core ==3.12.0
    - pip
  run:
    - python >={{ python_min }},<4.dev0
    - apache-airflow >=2.10.0
    - hvac >=1.1.0

test:
  imports:
    - airflow.providers.hashicorp
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/apache/airflow/
  summary: Provider package apache-airflow-providers-hashicorp for Apache Airflow
  license: Apache-2.0
  license_file: src/airflow/providers/hashicorp/LICENSE
  license_family: Apache
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-hashicorp/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
