{% set name = "apache-airflow-providers-hashicorp" %}
{% set version = "4.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/apache_airflow_providers_hashicorp-{{ version }}.tar.gz
  sha256: f764686fcf8222b8b80463fd5f6c69098cca5951a27a936bffd4ea8078ab4c4b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - flit-core ==3.10.0
    - pip
  run:
    - python >={{ python_min }},<4.dev0
    - apache-airflow >=2.9.0
    - hvac >=1.1.0

test:
  imports:
    - airflow.providers.hashicorp
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/apache/airflow/
  summary: Provider package apache-airflow-providers-hashicorp for Apache Airflow
  license: Apache-2.0
  license_file: airflow/providers/hashicorp/LICENSE
  license_family: Apache
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-hashicorp/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
